baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'My new Occult-eirbot Hugo site'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

[params]
  [params.contact]
    apiUrl = "http://localhost:3000"

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
