name = 'Occult-Eirbot'
license = 'MIT'
licenselink = 'https://github.com/eirbot/eirbot.eirb.fr/blob/master/themes/occult-eirbot/LICENSE'
description = 'Web layout for the Eirbot website'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/eirbot/eirbot.eirb.fr'

# If you have a running demo of the theme
demosite = 'https://eirbot.eirb.fr'

# Taxonomy terms
tags = ['blog', 'organization']
features = ['robotics', 'responsive', 'maintainable']

# If the theme has multiple authors
authors = [
  {name = 'Thomas Horrut', homepage = ''},
  {name = 'Tom Humbertclaude', homepage = ''}
]
